name: Nightly Wagtail test

on:
  schedule:
    - cron: "0 0 * * *"
    
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:10.8
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "psycopg2>=2.6"
          pip install "Django>=3.1,<3.2"
          pip install "git+https://github.com/wagtail/wagtail.git@master#egg=wagtail"
          pip install -e .[testing]
      - name: Test
        id: test
        continue-on-error: true
        run: |
          exit 1 && ./runtests.py
        env:
          DATABASE_ENGINE: django.db.backends.postgresql
          DATABASE_HOST: localhost
          DATABASE_USER: postgres
          DATABASE_PASS: postgres
          
      - name: Send Slack notification
        if: steps.test.outcome == "failure"
        run: |
          ./.github/report_nightly_build_failure.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
